### ISSUE TITLE
Issue switching from Auto to TeleOp in today's event

### ISSUE THREAD

**Issue by knightsean00** [Thunderbots5604/2015-Code#5] opened 2015-12-13 04:53 UTC
I also believe that we don't need two different Autonomous for the AutoSkydiverEncoder
We just used one and it worked fine today.

Beside the app issues....

**Comment by JakeOhara** [comment] 2015-12-13 05:26
We WILL need two autonomous programs, as the full function of the program is to reverse after dropping skydivers, and park on the mountain.

**Comment by JakeOhara** [comment] 2015-12-13 05:27
Also, we should test and change it so only the required servo is moving, just for simplicity.

**Comment by knightsean00** [comment] 2015-12-13 05:43
I noticed that

In my last commit I helped realize the full function of the program. We
won't know if it will work until Wednesday. It was just a rough estimation.

**Comment by JakeOhara** [comment] 2015-12-13 06:51
@PranavMathur @ZachOhara This essentially makes the mountain encoder autonomous useless, no? If it scores less points and is currently untested then what's the point?

**Comment by knightsean00** [comment] 2015-12-13 07:01
Just keep the mountain encoder autonomous, but remove the timed one, we
honestly don't need that one.

And yeah it should make it obsolete.

**Comment by PranavMathur** [comment] 2015-12-13 07:08
We still need the time autonomi. They are a backup.

**Comment by JakeOhara** [comment] 2015-12-13 07:12
At this point, the timed autonomous program(s) are far less accurate than our skydiver encoder autonomous, & it isn't currently known whether or not the timed programs still work. We should create a duplicate of the skydiver autonomous that only includes dropping skydivers, because that would be by far the most simple and reliable autonomous.

**Closed as completed** 2015-12-28 22:55 UTC
